SELECT
    DB_NAME,
    METRIC_NAME,
    SNAP_BEGIN_TIME,
    METRIC_VALUE_NUM,
    ANOMALY_FLAG,
    ANOMALY_TYPE,
    ANOMALY_SCORE
FROM AWR_DB_METRIC_TREND
WHERE ANOMALY_FLAG = 'Y'
ORDER BY SNAP_BEGIN_TIME DESC;
