--------------------------------------------------------------------------------
-- AWR SIZING ADVISOR
-- SCOPED HISTORICAL ANALYSIS VIEWS
-- View-first extension on top of ddlv2_final.sql + ddlv3 topology/platform
--------------------------------------------------------------------------------
spool ddlv4_views.log

CREATE OR REPLACE VIEW VW_AWR_SCOPE_CONTEXT AS
WITH latest_score_per_awr AS (
    SELECT
        sr.AWR_ID,
        sr.TOPOLOGY_CLASS,
        sr.PLATFORM_CLASS,
        sr.EVENT_CLASS,
        ROW_NUMBER() OVER (
            PARTITION BY sr.AWR_ID
            ORDER BY sr.SCORED_AT DESC, sr.SCORE_RESULT_ID DESC
        ) AS RN
    FROM AWR_SCORE_RESULT sr
)
SELECT
    r.AWR_ID,
    r.SOURCE_SYSTEM_ID,
    s.SOURCE_SYSTEM_CODE,
    COALESCE(r.DB_NAME, s.DB_NAME, s.DB_UNIQUE_NAME) AS DB_NAME,
    COALESCE(r.DBID, s.DBID) AS DBID,
    COALESCE(
        r.HOST_NAME,
        s.PRIMARY_HOST_NAME,
        JSON_VALUE(r.RAW_METADATA_JSON, '$.host_name' RETURNING VARCHAR2(256) NULL ON ERROR)
    ) AS HOST_NAME,
    COALESCE(
        r.INSTANCE_NAME,
        JSON_VALUE(r.RAW_METADATA_JSON, '$.instance_name' RETURNING VARCHAR2(128) NULL ON ERROR)
    ) AS INSTANCE_NAME,
    COALESCE(
        r.INSTANCE_NUMBER,
        JSON_VALUE(r.RAW_METADATA_JSON, '$.instance_number' RETURNING NUMBER NULL ON ERROR)
    ) AS INSTANCE_NUMBER,
    r.SNAP_TIME_BEGIN AS SNAP_BEGIN_TIME,
    r.SNAP_TIME_END AS SNAP_END_TIME,
    COALESCE(
        r.DB_VERSION,
        s.DB_VERSION,
        JSON_VALUE(r.RAW_METADATA_JSON, '$.db_version' RETURNING VARCHAR2(64) NULL ON ERROR)
    ) AS DB_VERSION,
    COALESCE(
        s.DATABASE_ROLE,
        JSON_VALUE(
            r.PARSER_OUTPUT_JSON,
            '$.topology_signals.database_role' RETURNING VARCHAR2(64) NULL ON ERROR
        ),
        JSON_VALUE(s.TAGS_JSON, '$.database_role' RETURNING VARCHAR2(64) NULL ON ERROR)
    ) AS DATABASE_ROLE,
    COALESCE(
        s.INSTANCE_COUNT,
        JSON_VALUE(
            r.PARSER_OUTPUT_JSON,
            '$.topology_signals.instance_count' RETURNING NUMBER NULL ON ERROR
        ),
        JSON_VALUE(s.TAGS_JSON, '$.instance_count' RETURNING NUMBER NULL ON ERROR)
    ) AS INSTANCE_COUNT,
    COALESCE(
        r.PLATFORM_NAME,
        s.PLATFORM_NAME,
        JSON_VALUE(r.RAW_METADATA_JSON, '$.platform' RETURNING VARCHAR2(256) NULL ON ERROR)
    ) AS PLATFORM,
    COALESCE(
        fv.TOPOLOGY_CLASS,
        ls.TOPOLOGY_CLASS,
        JSON_VALUE(
            r.PARSER_OUTPUT_JSON,
            '$.topology_signals.topology_class' RETURNING VARCHAR2(64) NULL ON ERROR
        ),
        JSON_VALUE(s.TAGS_JSON, '$.topology_class' RETURNING VARCHAR2(64) NULL ON ERROR)
    ) AS TOPOLOGY_CLASS,
    COALESCE(
        fv.PLATFORM_CLASS,
        ls.PLATFORM_CLASS,
        JSON_VALUE(
            r.PARSER_OUTPUT_JSON,
            '$.topology_signals.platform_class' RETURNING VARCHAR2(64) NULL ON ERROR
        ),
        JSON_VALUE(s.TAGS_JSON, '$.platform_class' RETURNING VARCHAR2(64) NULL ON ERROR)
    ) AS PLATFORM_CLASS
FROM AWR_REPORT r
JOIN AWR_SOURCE_SYSTEM s
  ON s.SOURCE_SYSTEM_ID = r.SOURCE_SYSTEM_ID
LEFT JOIN AWR_FEATURE_VECTOR fv
  ON fv.AWR_ID = r.AWR_ID
 AND fv.SOURCE_SYSTEM_ID = r.SOURCE_SYSTEM_ID
LEFT JOIN latest_score_per_awr ls
  ON ls.AWR_ID = r.AWR_ID
 AND ls.RN = 1;


CREATE OR REPLACE VIEW VW_AWR_METRIC_SCOPE AS
SELECT
    sc.AWR_ID,
    sc.SOURCE_SYSTEM_ID,
    sc.SOURCE_SYSTEM_CODE,
    sc.DB_NAME,
    sc.DBID,
    sc.HOST_NAME,
    sc.INSTANCE_NAME,
    sc.INSTANCE_NUMBER,
    sc.SNAP_BEGIN_TIME,
    sc.SNAP_END_TIME,
    sc.DB_VERSION,
    sc.DATABASE_ROLE,
    sc.INSTANCE_COUNT,
    sc.PLATFORM,
    sc.TOPOLOGY_CLASS,
    sc.PLATFORM_CLASS,
    mf.METRIC_FACT_ID,
    mf.METRIC_DOMAIN,
    mf.METRIC_NAME,
    mf.METRIC_SUBTYPE,
    mf.DIMENSION_1,
    mf.DIMENSION_2,
    mf.DIMENSION_3,
    mf.METRIC_VALUE_NUM,
    mf.METRIC_VALUE_TXT,
    mf.UNIT_OF_MEASURE,
    mf.VALUE_DIRECTION,
    mf.BASELINE_VALUE_NUM,
    mf.DELTA_VALUE_NUM,
    mf.ZSCORE_VALUE,
    mf.PERCENTILE_VALUE,
    mf.METRIC_JSON,
    mf.CREATED_AT
FROM AWR_METRIC_FACT mf
JOIN VW_AWR_SCOPE_CONTEXT sc
  ON sc.AWR_ID = mf.AWR_ID
 AND sc.SOURCE_SYSTEM_ID = mf.SOURCE_SYSTEM_ID;


CREATE OR REPLACE VIEW VW_AWR_SQL_SCOPE AS
SELECT
    sc.AWR_ID,
    sc.SOURCE_SYSTEM_ID,
    sc.SOURCE_SYSTEM_CODE,
    sc.DB_NAME,
    sc.DBID,
    sc.HOST_NAME,
    sc.INSTANCE_NAME,
    sc.INSTANCE_NUMBER,
    sc.SNAP_BEGIN_TIME,
    sc.SNAP_END_TIME,
    sc.DB_VERSION,
    sc.DATABASE_ROLE,
    sc.INSTANCE_COUNT,
    sc.PLATFORM,
    sc.TOPOLOGY_CLASS,
    sc.PLATFORM_CLASS,
    t.TOP_SQL_FACT_ID,
    t.SQL_ID,
    t.PLAN_HASH_VALUE,
    t.MODULE_NAME,
    t.PARSING_SCHEMA_NAME,
    t.RANK_BY_ELAPSED,
    t.RANK_BY_CPU,
    t.RANK_BY_GETS,
    t.RANK_BY_READS,
    t.RANK_BY_EXECUTIONS,
    t.ELAPSED_TIME_SEC,
    t.CPU_TIME_SEC,
    t.IO_TIME_SEC,
    t.BUFFER_GETS,
    t.DISK_READS,
    t.EXECUTIONS,
    t.ROWS_PROCESSED,
    t.ELAPSED_PER_EXEC_SEC,
    t.CPU_PER_EXEC_SEC,
    t.GETS_PER_EXEC,
    t.READS_PER_EXEC,
    t.SQL_TEXT_SHORT,
    t.SQL_TEXT_CLOB,
    t.SQL_METRICS_JSON,
    t.CREATED_AT
FROM AWR_TOP_SQL_FACT t
JOIN VW_AWR_SCOPE_CONTEXT sc
  ON sc.AWR_ID = t.AWR_ID
 AND sc.SOURCE_SYSTEM_ID = t.SOURCE_SYSTEM_ID;


CREATE OR REPLACE VIEW VW_AWR_WAIT_SCOPE AS
SELECT
    sc.AWR_ID,
    sc.SOURCE_SYSTEM_ID,
    sc.SOURCE_SYSTEM_CODE,
    sc.DB_NAME,
    sc.DBID,
    sc.HOST_NAME,
    sc.INSTANCE_NAME,
    sc.INSTANCE_NUMBER,
    sc.SNAP_BEGIN_TIME,
    sc.SNAP_END_TIME,
    sc.DB_VERSION,
    sc.DATABASE_ROLE,
    sc.INSTANCE_COUNT,
    sc.PLATFORM,
    sc.TOPOLOGY_CLASS,
    sc.PLATFORM_CLASS,
    w.WAIT_EVENT_FACT_ID,
    w.WAIT_CLASS,
    w.EVENT_NAME,
    w.TOTAL_WAITS,
    w.TOTAL_TIMEOUTS,
    w.TIME_WAITED_SEC,
    w.AVG_WAIT_MS,
    w.PCT_DB_TIME,
    w.RANK_IN_AWR,
    w.FOREGROUND_FLAG,
    w.WAIT_METRICS_JSON,
    w.CREATED_AT
FROM AWR_WAIT_EVENT_FACT w
JOIN VW_AWR_SCOPE_CONTEXT sc
  ON sc.AWR_ID = w.AWR_ID
 AND sc.SOURCE_SYSTEM_ID = w.SOURCE_SYSTEM_ID;


CREATE OR REPLACE VIEW VW_AWR_FEATURE_SCOPE AS
SELECT
    sc.AWR_ID,
    sc.SOURCE_SYSTEM_ID,
    sc.SOURCE_SYSTEM_CODE,
    sc.DB_NAME,
    sc.DBID,
    sc.HOST_NAME,
    sc.INSTANCE_NAME,
    sc.INSTANCE_NUMBER,
    sc.SNAP_BEGIN_TIME,
    sc.SNAP_END_TIME,
    sc.DB_VERSION,
    sc.DATABASE_ROLE,
    sc.INSTANCE_COUNT,
    sc.PLATFORM,
    sc.TOPOLOGY_CLASS,
    sc.PLATFORM_CLASS,
    fv.FEATURE_VECTOR_ID,
    fv.OBSERVED_AT,
    fv.VECTOR_VERSION,
    fv.FEATURE_SET_NAME,
    fv.FEATURE_SET_VERSION,
    fv.WORKLOAD_CLASS,
    fv.TOPOLOGY_CLASS AS FEATURE_TOPOLOGY_CLASS,
    fv.PLATFORM_CLASS AS FEATURE_PLATFORM_CLASS,
    fv.EVENT_CLASS AS FEATURE_EVENT_CLASS,
    fv.VECTOR_STATUS,
    fv.FEATURE_VECTOR,
    fv.NARRATIVE_EMBEDDING,
    fv.FEATURE_JSON,
    fv.NORMALIZATION_JSON,
    fv.EXPLANATION_JSON,
    fv.SOURCE_LINEAGE_JSON,
    fv.CREATED_AT
FROM AWR_FEATURE_VECTOR fv
JOIN VW_AWR_SCOPE_CONTEXT sc
  ON sc.AWR_ID = fv.AWR_ID
 AND sc.SOURCE_SYSTEM_ID = fv.SOURCE_SYSTEM_ID;


CREATE OR REPLACE VIEW VW_AWR_SCORE_SCOPE AS
SELECT
    sc.AWR_ID,
    sc.SOURCE_SYSTEM_ID,
    sc.SOURCE_SYSTEM_CODE,
    sc.DB_NAME,
    sc.DBID,
    sc.HOST_NAME,
    sc.INSTANCE_NAME,
    sc.INSTANCE_NUMBER,
    sc.SNAP_BEGIN_TIME,
    sc.SNAP_END_TIME,
    sc.DB_VERSION,
    sc.DATABASE_ROLE,
    sc.INSTANCE_COUNT,
    sc.PLATFORM,
    sc.TOPOLOGY_CLASS,
    sc.PLATFORM_CLASS,
    sr.SCORE_RESULT_ID,
    sr.FEATURE_VECTOR_ID,
    sr.SCORING_MODEL_ID,
    sm.MODEL_CODE,
    sm.MODEL_NAME,
    sm.MODEL_VERSION,
    sr.SCORED_AT,
    sr.DECISION_DOMAIN,
    sr.RISK_LEVEL,
    sr.TOTAL_SCORE,
    sr.CONFIDENCE_SCORE,
    sr.SEVERITY_SCORE,
    sr.URGENCY_SCORE,
    sr.BUSINESS_IMPACT_SCORE,
    sr.WORKLOAD_CLASS,
    sr.TOPOLOGY_CLASS AS SCORE_TOPOLOGY_CLASS,
    sr.PLATFORM_CLASS AS SCORE_PLATFORM_CLASS,
    sr.EVENT_CLASS,
    sr.PRIMARY_SIGNAL_DOMAIN,
    sr.EXPLANATION_JSON,
    sr.CONTRIBUTION_JSON,
    sr.SCORECARD_JSON,
    sr.CREATED_AT
FROM AWR_SCORE_RESULT sr
JOIN VW_AWR_SCOPE_CONTEXT sc
  ON sc.AWR_ID = sr.AWR_ID
 AND sc.SOURCE_SYSTEM_ID = sr.SOURCE_SYSTEM_ID
LEFT JOIN AWR_SCORING_MODEL sm
  ON sm.SCORING_MODEL_ID = sr.SCORING_MODEL_ID;

spool off
