SELECT
    FEATURE_VECTOR_ID,
    AWR_ID,
    SOURCE_SYSTEM_ID,
    OBSERVED_AT,
    VECTOR_VERSION,
    FEATURE_SET_NAME,
    FEATURE_SET_VERSION,
    WORKLOAD_CLASS,
    VECTOR_STATUS,
    TOPOLOGY_CLASS,
    PLATFORM_CLASS,
    EVENT_CLASS
FROM AWR_FEATURE_VECTOR
ORDER BY FEATURE_VECTOR_ID DESC
FETCH FIRST 10 ROWS ONLY;

SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'AWR_FEATURE_VECTOR'
  AND COLUMN_NAME IN ('FEATURE_VECTOR', 'NARRATIVE_EMBEDDING')
ORDER BY COLUMN_NAME;
