SELECT
    INGEST_RUN_ID,
    STATUS,
    STARTED_AT,
    ENDED_AT,
    FILE_COUNT,
    SUCCESS_COUNT,
    ERROR_COUNT,
    PIPELINE_NAME,
    PIPELINE_VERSION
FROM AWR_INGEST_RUN
ORDER BY INGEST_RUN_ID DESC
FETCH FIRST 10 ROWS ONLY;
