--------------------------------------------------------------------------------
-- patch_phase4e_feature_contract_global.sql
--
-- Purpose:
--   Apply additive Phase 4E feature-contract coverage for global
--   MEMORY / SGA / COMMIT / RAC contention signals without changing base
--   table structure.
--
-- Notes:
--   * Idempotent scoring-row inserts only.
--   * Replaces VW_AWR_FEATURE_METRIC_SCOPE to surface the new engineered
--     feature_json metrics for scope/trend/diagnostic consumers.
--   * Does not rebuild AWR_FEATURE_VECTOR or rescore AWR_SCORE_RESULT rows.
--------------------------------------------------------------------------------
SPOOL patch_phase4e_feature_contract_global.log
SET SQLBLANKLINES ON
SET DEFINE OFF
SET ECHO ON
SET TIMING ON
SET SERVEROUTPUT ON

--------------------------------------------------------------------------------
-- 1. ADD GLOBAL SCORING ROWS (IDEMPOTENT)
--------------------------------------------------------------------------------

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'HARD_PARSE_PCT',
    'Hard Parse Percentage',
    'MEMORY',
    '$.HARD_PARSE_PCT',
    0.03,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Light SGA parse-pressure weight for hard parse percentage'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'HARD_PARSE_PCT'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'TEMP_IO_PRESSURE',
    'TEMP I/O Pressure',
    'MEMORY',
    '$.TEMP_IO_PRESSURE',
    0.04,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Conservative memory pressure weight for TEMP spill I/O pressure'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'TEMP_IO_PRESSURE'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'FREE_BUFFER_WAIT_PRESSURE',
    'Free Buffer Wait Pressure',
    'MEMORY',
    '$.FREE_BUFFER_WAIT_PRESSURE',
    0.05,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Conservative memory pressure weight for free buffer wait contention'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'FREE_BUFFER_WAIT_PRESSURE'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'BUFFER_BUSY_PRESSURE',
    'Buffer Busy Pressure',
    'MEMORY',
    '$.BUFFER_BUSY_PRESSURE',
    0.05,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Conservative memory pressure weight for buffer busy contention'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'BUFFER_BUSY_PRESSURE'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'READ_BY_OTHER_SESSION_PRESSURE',
    'Read By Other Session Pressure',
    'IO',
    '$.READ_BY_OTHER_SESSION_PRESSURE',
    0.04,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Conservative I/O pressure weight for read by other session contention'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'READ_BY_OTHER_SESSION_PRESSURE'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'ENQUEUE_COMMIT_PRESSURE',
    'Enqueue Commit Pressure',
    'COMMIT',
    '$.ENQUEUE_COMMIT_PRESSURE',
    0.05,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Conservative commit pressure weight for enqueue contention'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'ENQUEUE_COMMIT_PRESSURE'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'REDO_CONTENTION_PRESSURE',
    'Redo Contention Pressure',
    'COMMIT',
    '$.REDO_CONTENTION_PRESSURE',
    0.04,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Conservative commit pressure weight for redo path contention'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'REDO_CONTENTION_PRESSURE'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'GC_BUFFER_BUSY_PCT_DB_TIME',
    'GC Buffer Busy Wait Pressure',
    'CLUSTER',
    '$.GC_BUFFER_BUSY_PCT_DB_TIME',
    0.05,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Conservative RAC pressure weight for GC buffer busy wait percentage'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'GC_BUFFER_BUSY_PCT_DB_TIME'
  );

INSERT INTO AWR_SCORING_WEIGHT (
    SCORING_MODEL_ID, FEATURE_CODE, FEATURE_NAME, FEATURE_DOMAIN, FEATURE_PATH,
    WEIGHT_VALUE, NORMALIZATION_METHOD, TRANSFORM_METHOD, POLARITY, NOTES
)
SELECT
    m.SCORING_MODEL_ID,
    'RAC_BUFFER_BUSY_PRESSURE',
    'RAC Buffer Busy Pressure',
    'CLUSTER',
    '$.RAC_BUFFER_BUSY_PRESSURE',
    0.04,
    'MINMAX',
    'NONE',
    'HIGH_BAD',
    'Conservative RAC pressure weight for RAC buffer busy contention'
FROM AWR_SCORING_MODEL m
WHERE m.MODEL_CODE = 'AWR_WEIGHTED_CORE'
  AND NOT EXISTS (
      SELECT 1
      FROM AWR_SCORING_WEIGHT w
      WHERE w.SCORING_MODEL_ID = m.SCORING_MODEL_ID
        AND w.FEATURE_CODE = 'RAC_BUFFER_BUSY_PRESSURE'
  );

COMMIT;

--------------------------------------------------------------------------------
-- 2. REPLACE FEATURE METRIC SCOPE VIEW
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW VW_AWR_FEATURE_METRIC_SCOPE AS
WITH feature_metric_base AS (
    SELECT
        fs.AWR_ID,
        fs.SOURCE_SYSTEM_ID,
        fs.DB_NAME,
        fs.DBID,
        fs.HOST_NAME,
        fs.INSTANCE_NAME,
        fs.INSTANCE_NUMBER,
        fs.SNAP_BEGIN_TIME,
        fs.SNAP_END_TIME,
        fs.DB_VERSION,
        fs.DATABASE_ROLE,
        fs.INSTANCE_COUNT,
        fs.PLATFORM,
        fs.TOPOLOGY_CLASS,
        fs.PLATFORM_CLASS,
        fs.FEATURE_VECTOR_ID,
        fs.OBSERVED_AT,
        jt.*
    FROM VW_AWR_FEATURE_SCOPE fs
    CROSS APPLY JSON_TABLE(
        fs.FEATURE_JSON,
        '$'
        COLUMNS (
            CPU_UTIL_P95 NUMBER PATH '$.CPU_UTIL_P95' NULL ON ERROR,
            DB_TIME_PER_TXN NUMBER PATH '$.DB_TIME_PER_TXN' NULL ON ERROR,
            DB_TIME_PER_SEC NUMBER PATH '$.db_time_per_sec' NULL ON ERROR,
            DB_CPU_PER_SEC NUMBER PATH '$.db_cpu_per_sec' NULL ON ERROR,
            READ_LATENCY_MS NUMBER PATH '$.READ_LATENCY_MS' NULL ON ERROR,
            LOG_FILE_SYNC_MS NUMBER PATH '$.LOG_FILE_SYNC_MS' NULL ON ERROR,
            TOP_SQL_LOAD_CONCENTRATION NUMBER PATH '$.TOP_SQL_LOAD_CONCENTRATION' NULL ON ERROR,
            HARD_PARSES_PER_SEC NUMBER PATH '$.HARD_PARSES_PER_SEC' NULL ON ERROR,
            HARD_PARSE_PCT NUMBER PATH '$.HARD_PARSE_PCT' NULL ON ERROR,
            THROUGHPUT_USER_CALLS_PER_SEC NUMBER PATH '$.THROUGHPUT_USER_CALLS_PER_SEC' NULL ON ERROR,
            TRANSACTIONS_PER_SEC NUMBER PATH '$.transactions_per_sec' NULL ON ERROR,
            TEMP_IO_PRESSURE NUMBER PATH '$.TEMP_IO_PRESSURE' NULL ON ERROR,
            PGA_SPILL_PRESSURE NUMBER PATH '$.PGA_SPILL_PRESSURE' NULL ON ERROR,
            BUFFER_CACHE_HIT_RATIO_PCT NUMBER PATH '$.BUFFER_CACHE_HIT_RATIO_PCT' NULL ON ERROR,
            LIBRARY_CACHE_HIT_RATIO_PCT NUMBER PATH '$.LIBRARY_CACHE_HIT_RATIO_PCT' NULL ON ERROR,
            WORKAREA_ONEPASS_PCT NUMBER PATH '$.WORKAREA_ONEPASS_PCT' NULL ON ERROR,
            WORKAREA_MULTIPASS_PCT NUMBER PATH '$.WORKAREA_MULTIPASS_PCT' NULL ON ERROR,
            FREE_BUFFER_WAIT_PRESSURE NUMBER PATH '$.FREE_BUFFER_WAIT_PRESSURE' NULL ON ERROR,
            BUFFER_BUSY_PRESSURE NUMBER PATH '$.BUFFER_BUSY_PRESSURE' NULL ON ERROR,
            READ_BY_OTHER_SESSION_PRESSURE NUMBER PATH '$.READ_BY_OTHER_SESSION_PRESSURE' NULL ON ERROR,
            ENQUEUE_COMMIT_PRESSURE NUMBER PATH '$.ENQUEUE_COMMIT_PRESSURE' NULL ON ERROR,
            REDO_CONTENTION_PRESSURE NUMBER PATH '$.REDO_CONTENTION_PRESSURE' NULL ON ERROR,
            USER_IO_PRESSURE NUMBER PATH '$.USER_IO_PRESSURE' NULL ON ERROR,
            COMMIT_PRESSURE NUMBER PATH '$.COMMIT_PRESSURE' NULL ON ERROR,
            CONCURRENCY_PRESSURE NUMBER PATH '$.CONCURRENCY_PRESSURE' NULL ON ERROR,
            READ_MB_PER_SEC NUMBER PATH '$.READ_MB_PER_SEC' NULL ON ERROR,
            WRITE_MB_PER_SEC NUMBER PATH '$.WRITE_MB_PER_SEC' NULL ON ERROR,
            CLUSTER_WAIT_PCT_DB_TIME NUMBER PATH '$.CLUSTER_WAIT_PCT_DB_TIME' NULL ON ERROR,
            GC_CR_WAIT_PCT_DB_TIME NUMBER PATH '$.GC_CR_WAIT_PCT_DB_TIME' NULL ON ERROR,
            GC_CURRENT_WAIT_PCT_DB_TIME NUMBER PATH '$.GC_CURRENT_WAIT_PCT_DB_TIME' NULL ON ERROR,
            GC_BUFFER_BUSY_PCT_DB_TIME NUMBER PATH '$.GC_BUFFER_BUSY_PCT_DB_TIME' NULL ON ERROR,
            RAC_BUFFER_BUSY_PRESSURE NUMBER PATH '$.RAC_BUFFER_BUSY_PRESSURE' NULL ON ERROR,
            INTERCONNECT_STRESS_FLAG NUMBER PATH '$.INTERCONNECT_STRESS_FLAG' NULL ON ERROR,
            RAC_CONTENTION_FLAG NUMBER PATH '$.RAC_CONTENTION_FLAG' NULL ON ERROR,
            EXA_CELL_IO_PCT_DB_TIME NUMBER PATH '$.EXA_CELL_IO_PCT_DB_TIME' NULL ON ERROR,
            EXA_OFFLOAD_EFFICIENCY NUMBER PATH '$.EXA_OFFLOAD_EFFICIENCY' NULL ON ERROR,
            EXA_STORAGE_INDEX_SAVINGS NUMBER PATH '$.EXA_STORAGE_INDEX_SAVINGS' NULL ON ERROR,
            SMART_SCAN_FLAG NUMBER PATH '$.SMART_SCAN_FLAG' NULL ON ERROR,
            FLASH_CACHE_HIT_FLAG NUMBER PATH '$.flash_cache_hit_flag' NULL ON ERROR,
            EXADATA_IO_BENEFIT_FLAG NUMBER PATH '$.exadata_io_benefit_flag' NULL ON ERROR,
            TRANSPORT_LAG_SEC NUMBER PATH '$.TRANSPORT_LAG_SEC' NULL ON ERROR,
            APPLY_LAG_SEC NUMBER PATH '$.APPLY_LAG_SEC' NULL ON ERROR,
            REDO_TRANSPORT_ISSUE_FLAG NUMBER PATH '$.REDO_TRANSPORT_ISSUE_FLAG' NULL ON ERROR,
            FAILOVER_EVENT_FLAG NUMBER PATH '$.FAILOVER_EVENT_FLAG' NULL ON ERROR,
            ROLE_TRANSITION_FLAG NUMBER PATH '$.ROLE_TRANSITION_FLAG' NULL ON ERROR,
            POST_FAILOVER_RECOVERY_FLAG NUMBER PATH '$.POST_FAILOVER_RECOVERY_FLAG' NULL ON ERROR
        )
    ) jt
),
feature_metric_unpivot AS (
    SELECT
        AWR_ID,
        SOURCE_SYSTEM_ID,
        DB_NAME,
        DBID,
        HOST_NAME,
        INSTANCE_NAME,
        INSTANCE_NUMBER,
        SNAP_BEGIN_TIME,
        SNAP_END_TIME,
        DB_VERSION,
        DATABASE_ROLE,
        INSTANCE_COUNT,
        PLATFORM,
        TOPOLOGY_CLASS,
        PLATFORM_CLASS,
        FEATURE_VECTOR_ID,
        OBSERVED_AT,
        METRIC_NAME,
        METRIC_VALUE_NUM
    FROM feature_metric_base
    UNPIVOT (
        METRIC_VALUE_NUM FOR METRIC_NAME IN (
            CPU_UTIL_P95,
            DB_TIME_PER_TXN,
            DB_TIME_PER_SEC,
            DB_CPU_PER_SEC,
            READ_LATENCY_MS,
            LOG_FILE_SYNC_MS,
            TOP_SQL_LOAD_CONCENTRATION,
            HARD_PARSES_PER_SEC,
            HARD_PARSE_PCT,
            THROUGHPUT_USER_CALLS_PER_SEC,
            TRANSACTIONS_PER_SEC,
            TEMP_IO_PRESSURE,
            PGA_SPILL_PRESSURE,
            BUFFER_CACHE_HIT_RATIO_PCT,
            LIBRARY_CACHE_HIT_RATIO_PCT,
            WORKAREA_ONEPASS_PCT,
            WORKAREA_MULTIPASS_PCT,
            FREE_BUFFER_WAIT_PRESSURE,
            BUFFER_BUSY_PRESSURE,
            READ_BY_OTHER_SESSION_PRESSURE,
            ENQUEUE_COMMIT_PRESSURE,
            REDO_CONTENTION_PRESSURE,
            USER_IO_PRESSURE,
            COMMIT_PRESSURE,
            CONCURRENCY_PRESSURE,
            READ_MB_PER_SEC,
            WRITE_MB_PER_SEC,
            CLUSTER_WAIT_PCT_DB_TIME,
            GC_CR_WAIT_PCT_DB_TIME,
            GC_CURRENT_WAIT_PCT_DB_TIME,
            GC_BUFFER_BUSY_PCT_DB_TIME,
            RAC_BUFFER_BUSY_PRESSURE,
            INTERCONNECT_STRESS_FLAG,
            RAC_CONTENTION_FLAG,
            EXA_CELL_IO_PCT_DB_TIME,
            EXA_OFFLOAD_EFFICIENCY,
            EXA_STORAGE_INDEX_SAVINGS,
            SMART_SCAN_FLAG,
            FLASH_CACHE_HIT_FLAG,
            EXADATA_IO_BENEFIT_FLAG,
            TRANSPORT_LAG_SEC,
            APPLY_LAG_SEC,
            REDO_TRANSPORT_ISSUE_FLAG,
            FAILOVER_EVENT_FLAG,
            ROLE_TRANSITION_FLAG,
            POST_FAILOVER_RECOVERY_FLAG
        )
    )
)
SELECT
    AWR_ID,
    SOURCE_SYSTEM_ID,
    DB_NAME,
    DBID,
    HOST_NAME,
    INSTANCE_NAME,
    INSTANCE_NUMBER,
    SNAP_BEGIN_TIME,
    SNAP_END_TIME,
    DB_VERSION,
    DATABASE_ROLE,
    INSTANCE_COUNT,
    PLATFORM,
    TOPOLOGY_CLASS,
    PLATFORM_CLASS,
    METRIC_NAME,
    'DB' AS METRIC_SCOPE,
    CASE
        WHEN METRIC_NAME IN (
            'CPU_UTIL_P95',
            'DB_TIME_PER_TXN',
            'DB_TIME_PER_SEC',
            'DB_CPU_PER_SEC',
            'READ_LATENCY_MS',
            'LOG_FILE_SYNC_MS',
            'TOP_SQL_LOAD_CONCENTRATION',
            'HARD_PARSES_PER_SEC',
            'HARD_PARSE_PCT',
            'THROUGHPUT_USER_CALLS_PER_SEC',
            'TRANSACTIONS_PER_SEC',
            'TEMP_IO_PRESSURE',
            'PGA_SPILL_PRESSURE',
            'BUFFER_CACHE_HIT_RATIO_PCT',
            'LIBRARY_CACHE_HIT_RATIO_PCT',
            'WORKAREA_ONEPASS_PCT',
            'WORKAREA_MULTIPASS_PCT',
            'FREE_BUFFER_WAIT_PRESSURE',
            'BUFFER_BUSY_PRESSURE',
            'READ_BY_OTHER_SESSION_PRESSURE',
            'ENQUEUE_COMMIT_PRESSURE',
            'REDO_CONTENTION_PRESSURE',
            'USER_IO_PRESSURE',
            'COMMIT_PRESSURE',
            'CONCURRENCY_PRESSURE',
            'READ_MB_PER_SEC',
            'WRITE_MB_PER_SEC'
        ) THEN 'GENERAL'
        WHEN METRIC_NAME IN (
            'CLUSTER_WAIT_PCT_DB_TIME',
            'GC_CR_WAIT_PCT_DB_TIME',
            'GC_CURRENT_WAIT_PCT_DB_TIME',
            'GC_BUFFER_BUSY_PCT_DB_TIME',
            'RAC_BUFFER_BUSY_PRESSURE',
            'INTERCONNECT_STRESS_FLAG',
            'RAC_CONTENTION_FLAG'
        ) THEN 'RAC_CLUSTER'
        WHEN METRIC_NAME IN (
            'EXA_CELL_IO_PCT_DB_TIME',
            'EXA_OFFLOAD_EFFICIENCY',
            'EXA_STORAGE_INDEX_SAVINGS',
            'SMART_SCAN_FLAG',
            'FLASH_CACHE_HIT_FLAG',
            'EXADATA_IO_BENEFIT_FLAG'
        ) THEN 'EXADATA'
        WHEN METRIC_NAME IN (
            'TRANSPORT_LAG_SEC',
            'APPLY_LAG_SEC',
            'REDO_TRANSPORT_ISSUE_FLAG'
        ) THEN 'DATA_GUARD'
        ELSE 'TOPOLOGY_EVENT'
    END AS METRIC_CATEGORY,
    METRIC_VALUE_NUM,
    FEATURE_VECTOR_ID,
    OBSERVED_AT
FROM feature_metric_unpivot
WHERE METRIC_VALUE_NUM IS NOT NULL;

PROMPT
PROMPT ==========================================
PROMPT PATCH PHASE 4E FEATURE CONTRACT VALIDATION
PROMPT ==========================================

SELECT FEATURE_CODE, FEATURE_DOMAIN, WEIGHT_VALUE
FROM AWR_SCORING_WEIGHT
WHERE FEATURE_CODE IN (
    'HARD_PARSE_PCT',
    'TEMP_IO_PRESSURE',
    'FREE_BUFFER_WAIT_PRESSURE',
    'BUFFER_BUSY_PRESSURE',
    'READ_BY_OTHER_SESSION_PRESSURE',
    'ENQUEUE_COMMIT_PRESSURE',
    'REDO_CONTENTION_PRESSURE',
    'GC_BUFFER_BUSY_PCT_DB_TIME',
    'RAC_BUFFER_BUSY_PRESSURE'
)
ORDER BY FEATURE_CODE;

SPOOL OFF
