SELECT
    SCORING_MODEL_ID,
    FEATURE_CODE,
    FEATURE_NAME,
    FEATURE_DOMAIN,
    WEIGHT_VALUE,
    NORMALIZATION_METHOD,
    TRANSFORM_METHOD,
    POLARITY,
    ENABLED_FLAG
FROM AWR_SCORING_WEIGHT
WHERE SCORING_MODEL_ID = 1
ORDER BY FEATURE_DOMAIN, FEATURE_CODE;
