SELECT
    DB_NAME,
    DBID,
    METRIC_NAME,
    SNAP_BEGIN_TIME,
    METRIC_VALUE_NUM,
    ROLLING_MEAN,
    ROLLING_STD,
    SLOPE,
    PERCENT_CHANGE,
    ANOMALY_FLAG,
    ANOMALY_TYPE
FROM AWR_DB_METRIC_TREND
ORDER BY SNAP_BEGIN_TIME DESC
FETCH FIRST 20 ROWS ONLY;
