"""Centralized engineered metric catalog for DB-scoped history rendering."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class EngineeredMetricDefinition:
    metric_name: str
    display_label: str
    metric_category: str
    unit: str
    numeric_format: str
    directionality: str
    domain: str
    chart_title: str
    chart_label: str
    color: str
    implemented: bool
    source_metric_name: str | None = None
    reason_unavailable: str | None = None
    related_domains: tuple[str, ...] = ()


DOMAIN_DISPLAY_ORDER = (
    "CPU",
    "IO",
    "MEMORY",
    "NETWORK",
    "RAC",
    "EXADATA",
    "DATAGUARD",
)


ENGINEERED_METRIC_CATALOG: tuple[EngineeredMetricDefinition, ...] = (
    EngineeredMetricDefinition(
        metric_name="CPU_UTIL_P95",
        display_label="CPU Util P95",
        metric_category="CAPACITY",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="CPU",
        chart_title="CPU Util P95",
        chart_label="CPU util %",
        color="rgba(255, 107, 107, 0.92)",
        implemented=True,
        source_metric_name="CPU_UTIL_P95",
    ),
    EngineeredMetricDefinition(
        metric_name="CPU_UTIL_AVG",
        display_label="CPU Util Avg",
        metric_category="CAPACITY",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="CPU",
        chart_title="CPU Util Avg",
        chart_label="CPU util avg %",
        color="rgba(255, 99, 132, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Current DB-scoped feature pipeline does not persist a true average CPU utilization metric."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="DB_CPU_PCT_DB_TIME",
        display_label="DB CPU % DB Time",
        metric_category="SATURATION",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="CPU",
        chart_title="DB CPU % DB Time",
        chart_label="DB CPU % DB time",
        color="rgba(255, 82, 82, 0.92)",
        implemented=True,
        source_metric_name="DB_CPU_PCT_DB_TIME",
    ),
    EngineeredMetricDefinition(
        metric_name="READ_LATENCY_MS",
        display_label="Read Latency",
        metric_category="LATENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="Read Latency",
        chart_label="Read latency ms",
        color="rgba(255, 159, 67, 0.92)",
        implemented=True,
        source_metric_name="READ_LATENCY_MS",
    ),
    EngineeredMetricDefinition(
        metric_name="WRITE_LATENCY_MS",
        display_label="Write Latency",
        metric_category="LATENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="Write Latency",
        chart_label="Write latency ms",
        color="rgba(255, 145, 77, 0.92)",
        implemented=True,
        source_metric_name="WRITE_LATENCY_MS",
    ),
    EngineeredMetricDefinition(
        metric_name="TEMP_WRITE_LATENCY_MS",
        display_label="TEMP Write Latency",
        metric_category="LATENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="TEMP Write Latency",
        chart_label="TEMP write latency ms",
        color="rgba(255, 177, 66, 0.92)",
        implemented=True,
        source_metric_name="TEMP_WRITE_LATENCY_MS",
    ),
    EngineeredMetricDefinition(
        metric_name="LOG_FILE_SYNC_MS",
        display_label="Log File Sync",
        metric_category="COMMIT",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="Commit / Log File Sync",
        chart_label="Log file sync ms",
        color="rgba(246, 184, 76, 0.92)",
        implemented=True,
        source_metric_name="LOG_FILE_SYNC_MS",
    ),
    EngineeredMetricDefinition(
        metric_name="LOG_WRITE_LATENCY_MS",
        display_label="Log Write Latency",
        metric_category="COMMIT",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="Log Write Latency",
        chart_label="Log write latency ms",
        color="rgba(245, 200, 110, 0.92)",
        implemented=True,
        source_metric_name="LOG_WRITE_LATENCY_MS",
    ),
    EngineeredMetricDefinition(
        metric_name="REDO_GENERATION_PER_SEC",
        display_label="Redo Generation / Sec",
        metric_category="THROUGHPUT",
        unit="bytes_per_sec",
        numeric_format="bytes_per_sec_1",
        directionality="NEUTRAL",
        domain="IO",
        chart_title="Redo Generation Rate",
        chart_label="Redo bytes/s",
        color="rgba(255, 214, 102, 0.92)",
        implemented=True,
        source_metric_name="REDO_GENERATION_PER_SEC",
    ),
    EngineeredMetricDefinition(
        metric_name="USER_IO_PRESSURE",
        display_label="User I/O Pressure",
        metric_category="WAIT",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="User I/O Pressure",
        chart_label="User I/O % DB time",
        color="rgba(255, 171, 64, 0.92)",
        implemented=True,
        source_metric_name="USER_IO_PRESSURE",
    ),
    EngineeredMetricDefinition(
        metric_name="COMMIT_PRESSURE",
        display_label="Commit Pressure",
        metric_category="WAIT",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="Commit Pressure",
        chart_label="Commit % DB time",
        color="rgba(255, 202, 40, 0.92)",
        implemented=True,
        source_metric_name="COMMIT_PRESSURE",
    ),
    EngineeredMetricDefinition(
        metric_name="READ_MB_PER_SEC",
        display_label="Read MB / Sec",
        metric_category="THROUGHPUT",
        unit="mb_per_sec",
        numeric_format="mbps_2",
        directionality="NEUTRAL",
        domain="IO",
        chart_title="Read Throughput",
        chart_label="Read MB/s",
        color="rgba(255, 183, 77, 0.92)",
        implemented=True,
        source_metric_name="READ_MB_PER_SEC",
    ),
    EngineeredMetricDefinition(
        metric_name="WRITE_MB_PER_SEC",
        display_label="Write MB / Sec",
        metric_category="THROUGHPUT",
        unit="mb_per_sec",
        numeric_format="mbps_2",
        directionality="NEUTRAL",
        domain="IO",
        chart_title="Write Throughput",
        chart_label="Write MB/s",
        color="rgba(255, 204, 128, 0.92)",
        implemented=True,
        source_metric_name="WRITE_MB_PER_SEC",
    ),
    EngineeredMetricDefinition(
        metric_name="WRITE_IO_PCT",
        display_label="Write I/O %",
        metric_category="BALANCE",
        unit="percent",
        numeric_format="pct_1",
        directionality="NEUTRAL",
        domain="IO",
        chart_title="Write I/O %",
        chart_label="Write I/O %",
        color="rgba(255, 183, 77, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Current feature pipeline does not persist a deterministic write-I/O percentage metric."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="TOP_SQL_LOAD_CONCENTRATION",
        display_label="Top SQL Load Concentration",
        metric_category="CONCENTRATION",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="Top 3 SQL Share",
        chart_label="Top 3 SQL share %",
        color="rgba(186, 104, 200, 0.92)",
        implemented=True,
        source_metric_name="TOP_SQL_LOAD_CONCENTRATION",
    ),
    EngineeredMetricDefinition(
        metric_name="BUFFER_CACHE_HIT_RATIO_PCT",
        display_label="Buffer Cache Hit Ratio",
        metric_category="EFFICIENCY",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="MEMORY",
        chart_title="Buffer Cache Hit Ratio",
        chart_label="Buffer cache hit %",
        color="rgba(129, 199, 132, 0.92)",
        implemented=True,
        source_metric_name="BUFFER_CACHE_HIT_RATIO_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="LIBRARY_CACHE_HIT_RATIO_PCT",
        display_label="Library Cache Hit Ratio",
        metric_category="EFFICIENCY",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="MEMORY",
        chart_title="Library Cache Hit Ratio",
        chart_label="Library cache hit %",
        color="rgba(102, 187, 106, 0.92)",
        implemented=True,
        source_metric_name="LIBRARY_CACHE_HIT_RATIO_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="HARD_PARSE_PCT",
        display_label="Hard Parse %",
        metric_category="PARSE",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="Hard Parse %",
        chart_label="Hard parse %",
        color="rgba(76, 175, 80, 0.92)",
        implemented=True,
        source_metric_name="HARD_PARSE_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="PARSE_CPU_TO_PARSE_ELAPSED_PCT",
        display_label="Parse CPU / Parse Elapsed %",
        metric_category="PARSE",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="MEMORY",
        chart_title="Parse CPU / Parse Elapsed",
        chart_label="Parse CPU / parse elapsed %",
        color="rgba(56, 142, 60, 0.92)",
        implemented=True,
        source_metric_name="PARSE_CPU_TO_PARSE_ELAPSED_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="SHARED_POOL_FREE_PCT",
        display_label="Shared Pool Free %",
        metric_category="MEMORY",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="MEMORY",
        chart_title="Shared Pool Free %",
        chart_label="Shared pool free %",
        color="rgba(46, 125, 50, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Shared-pool free percentage is not currently parsed into the DB-scoped feature layer."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="PGA_CACHE_HIT_PCT",
        display_label="PGA Cache Hit %",
        metric_category="EFFICIENCY",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="MEMORY",
        chart_title="PGA Cache Hit %",
        chart_label="PGA cache hit %",
        color="rgba(38, 166, 154, 0.92)",
        implemented=True,
        source_metric_name="PGA_CACHE_HIT_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="TEMP_SPILL_PCT",
        display_label="Temp Spill %",
        metric_category="SPILL",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="TEMP Spill %",
        chart_label="TEMP spill %",
        color="rgba(0, 172, 193, 0.92)",
        implemented=True,
        source_metric_name="TEMP_SPILL_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="SORTS_DISK_PCT",
        display_label="Sorts to Disk %",
        metric_category="SPILL",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="Sorts to Disk %",
        chart_label="Sorts to disk %",
        color="rgba(0, 151, 167, 0.92)",
        implemented=True,
        source_metric_name="SORTS_DISK_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="CURSOR_MUTEX_WAIT_PCT_DB_TIME",
        display_label="Cursor Mutex Wait %",
        metric_category="CONTENTION",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="Cursor Mutex Wait %",
        chart_label="Cursor mutex % DB time",
        color="rgba(77, 182, 172, 0.92)",
        implemented=True,
        source_metric_name="CURSOR_MUTEX_WAIT_PCT_DB_TIME",
    ),
    EngineeredMetricDefinition(
        metric_name="HARD_PARSES_PER_SEC",
        display_label="Hard Parses / Sec",
        metric_category="PARSE",
        unit="per_sec",
        numeric_format="num_2",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="Hard Parses / Sec",
        chart_label="Hard parses / s",
        color="rgba(102, 187, 106, 0.92)",
        implemented=True,
        source_metric_name="HARD_PARSES_PER_SEC",
    ),
    EngineeredMetricDefinition(
        metric_name="PGA_SPILL_PRESSURE",
        display_label="PGA Spill Pressure",
        metric_category="SPILL",
        unit="ratio",
        numeric_format="ratio_3",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="PGA Spill Pressure",
        chart_label="PGA spill pressure",
        color="rgba(0, 172, 193, 0.92)",
        implemented=True,
        source_metric_name="PGA_SPILL_PRESSURE",
    ),
    EngineeredMetricDefinition(
        metric_name="TEMP_IO_PRESSURE",
        display_label="TEMP I/O Pressure",
        metric_category="SPILL",
        unit="per_sec",
        numeric_format="num_2",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="TEMP I/O Pressure",
        chart_label="TEMP I/O pressure",
        color="rgba(38, 198, 218, 0.92)",
        implemented=True,
        source_metric_name="TEMP_IO_PRESSURE",
    ),
    EngineeredMetricDefinition(
        metric_name="CONCURRENCY_PRESSURE",
        display_label="Concurrency Pressure",
        metric_category="CONTENTION",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="Concurrency Pressure",
        chart_label="Concurrency % DB time",
        color="rgba(77, 208, 225, 0.92)",
        implemented=True,
        source_metric_name="CONCURRENCY_PRESSURE",
    ),
    EngineeredMetricDefinition(
        metric_name="GC_TRAFFIC_PER_SEC",
        display_label="GC Traffic / Sec",
        metric_category="TRAFFIC",
        unit="per_sec",
        numeric_format="num_2",
        directionality="HIGH_IS_BAD",
        domain="NETWORK",
        chart_title="GC Traffic / Sec",
        chart_label="GC traffic / s",
        color="rgba(90, 209, 255, 0.92)",
        implemented=False,
        reason_unavailable=(
            "GC traffic per second is not currently extracted into FEATURE_JSON or the DB-scope view."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="REMOTE_BLOCK_PCT",
        display_label="Remote Block %",
        metric_category="TRAFFIC",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="NETWORK",
        chart_title="Remote Block %",
        chart_label="Remote block %",
        color="rgba(79, 195, 247, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Remote block percentage is not currently derivable from the persisted DB-scoped feature set."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="REDO_TRANSPORT_RATE_MBPS",
        display_label="Redo Transport Rate",
        metric_category="THROUGHPUT",
        unit="mbps",
        numeric_format="mbps_2",
        directionality="NEUTRAL",
        domain="NETWORK",
        chart_title="Redo Transport Rate",
        chart_label="Redo transport MB/s",
        color="rgba(41, 182, 246, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Redo transport rate is not currently parsed or persisted into the DB-scoped engineered feature set."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="NETWORK_WAIT_PCT_DB_TIME",
        display_label="Network Wait %",
        metric_category="WAIT",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="NETWORK",
        chart_title="Network Wait %",
        chart_label="Network % DB time",
        color="rgba(3, 169, 244, 0.92)",
        implemented=True,
        source_metric_name="NETWORK_WAIT_PCT_DB_TIME",
        related_domains=("RAC", "DATAGUARD"),
    ),
    EngineeredMetricDefinition(
        metric_name="CLUSTER_WAIT_PCT_DB_TIME",
        display_label="Cluster Wait %",
        metric_category="WAIT",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="RAC",
        chart_title="Cluster Wait %",
        chart_label="Cluster waits % DB time",
        color="rgba(129, 199, 132, 0.92)",
        implemented=True,
        source_metric_name="CLUSTER_WAIT_PCT_DB_TIME",
        related_domains=("NETWORK",),
    ),
    EngineeredMetricDefinition(
        metric_name="GC_CR_WAIT_PCT_DB_TIME",
        display_label="GC CR Wait %",
        metric_category="WAIT",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="RAC",
        chart_title="GC CR Wait %",
        chart_label="GC CR % DB time",
        color="rgba(77, 182, 172, 0.92)",
        implemented=True,
        source_metric_name="GC_CR_WAIT_PCT_DB_TIME",
        related_domains=("NETWORK",),
    ),
    EngineeredMetricDefinition(
        metric_name="GC_CURRENT_WAIT_PCT_DB_TIME",
        display_label="GC Current Wait %",
        metric_category="WAIT",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="RAC",
        chart_title="GC Current Wait %",
        chart_label="GC current % DB time",
        color="rgba(38, 166, 154, 0.92)",
        implemented=True,
        source_metric_name="GC_CURRENT_WAIT_PCT_DB_TIME",
        related_domains=("NETWORK",),
    ),
    EngineeredMetricDefinition(
        metric_name="GC_BUFFER_BUSY_PCT_DB_TIME",
        display_label="GC Buffer Busy %",
        metric_category="CONTENTION",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="RAC",
        chart_title="GC Buffer Busy %",
        chart_label="GC buffer busy % DB time",
        color="rgba(0, 150, 136, 0.92)",
        implemented=True,
        source_metric_name="GC_BUFFER_BUSY_PCT_DB_TIME",
        related_domains=("NETWORK",),
    ),
    EngineeredMetricDefinition(
        metric_name="EXA_CELL_IO_PCT_DB_TIME",
        display_label="Exadata Cell I/O %",
        metric_category="WAIT",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="EXADATA",
        chart_title="Exadata Cell I/O %",
        chart_label="Cell I/O % DB time",
        color="rgba(171, 71, 188, 0.92)",
        implemented=True,
        source_metric_name="EXA_CELL_IO_PCT_DB_TIME",
    ),
    EngineeredMetricDefinition(
        metric_name="EXA_OFFLOAD_EFFICIENCY",
        display_label="Exadata Offload Efficiency",
        metric_category="EFFICIENCY",
        unit="ratio",
        numeric_format="ratio_pct_1",
        directionality="LOW_IS_BAD",
        domain="EXADATA",
        chart_title="Exadata Offload Efficiency",
        chart_label="Offload efficiency",
        color="rgba(156, 39, 176, 0.92)",
        implemented=True,
        source_metric_name="EXA_OFFLOAD_EFFICIENCY",
    ),
    EngineeredMetricDefinition(
        metric_name="TRANSPORT_LAG_SEC",
        display_label="Transport Lag",
        metric_category="LAG",
        unit="seconds",
        numeric_format="sec_1",
        directionality="HIGH_IS_BAD",
        domain="DATAGUARD",
        chart_title="Data Guard Transport Lag",
        chart_label="Transport lag sec",
        color="rgba(255, 213, 79, 0.92)",
        implemented=True,
        source_metric_name="TRANSPORT_LAG_SEC",
    ),
    EngineeredMetricDefinition(
        metric_name="APPLY_LAG_SEC",
        display_label="Apply Lag",
        metric_category="LAG",
        unit="seconds",
        numeric_format="sec_1",
        directionality="HIGH_IS_BAD",
        domain="DATAGUARD",
        chart_title="Data Guard Apply Lag",
        chart_label="Apply lag sec",
        color="rgba(255, 193, 7, 0.92)",
        implemented=True,
        source_metric_name="APPLY_LAG_SEC",
    ),
    EngineeredMetricDefinition(
        metric_name="CPU_SATURATION_PCT",
        display_label="CPU Saturation %",
        metric_category="SATURATION",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="CPU",
        chart_title="CPU Saturation %",
        chart_label="CPU saturation %",
        color="rgba(239, 83, 80, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Current feature layer does not persist a separate CPU saturation "
            "metric beyond CPU proxies already surfaced."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="CPU_PER_EXECUTION_MS",
        display_label="CPU per Execution",
        metric_category="EFFICIENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="CPU",
        chart_title="CPU per Execution",
        chart_label="CPU / execution ms",
        color="rgba(244, 67, 54, 0.92)",
        implemented=False,
        reason_unavailable=(
            "CPU per execution is not currently persisted in the DB-scoped engineered feature layer."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="DIRTY_BUFFER_PRESSURE_PCT",
        display_label="Dirty Buffer Pressure",
        metric_category="PRESSURE",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="Dirty Buffer Pressure",
        chart_label="Dirty buffer pressure %",
        color="rgba(255, 171, 64, 0.92)",
        implemented=False,
        reason_unavailable="Not currently derived from the persisted feature layer.",
    ),
    EngineeredMetricDefinition(
        metric_name="TEMP_IO_PCT",
        display_label="TEMP I/O %",
        metric_category="PRESSURE",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="TEMP I/O %",
        chart_label="TEMP I/O %",
        color="rgba(255, 204, 128, 0.92)",
        implemented=False,
        reason_unavailable="TEMP I/O percentage is not currently a first-class DB-scoped engineered metric.",
    ),
    EngineeredMetricDefinition(
        metric_name="DBWR_CHECKPOINT_PRESSURE_PCT",
        display_label="DBWR Checkpoint Pressure",
        metric_category="PRESSURE",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="IO",
        chart_title="DBWR Checkpoint Pressure",
        chart_label="Checkpoint pressure %",
        color="rgba(255, 202, 40, 0.92)",
        implemented=False,
        reason_unavailable="Checkpoint pressure is not currently parsed into the DB-scoped feature layer.",
    ),
    EngineeredMetricDefinition(
        metric_name="SOFT_PARSE_PCT",
        display_label="Soft Parse %",
        metric_category="PARSE",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="MEMORY",
        chart_title="Soft Parse %",
        chart_label="Soft parse %",
        color="rgba(67, 160, 71, 0.92)",
        implemented=True,
        source_metric_name="SOFT_PARSE_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="SESSION_CURSOR_CACHE_HIT_PCT",
        display_label="Session Cursor Cache Hit %",
        metric_category="PARSE",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="MEMORY",
        chart_title="Session Cursor Cache Hit %",
        chart_label="Session cursor cache hit %",
        color="rgba(76, 175, 80, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Session cursor cache hit percentage is not currently extracted into FEATURE_JSON."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="RELOADS_PCT",
        display_label="Reloads %",
        metric_category="PARSE",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="Reloads %",
        chart_label="Reloads %",
        color="rgba(139, 195, 74, 0.92)",
        implemented=False,
        reason_unavailable="Reload percentage is not currently parsed or persisted.",
    ),
    EngineeredMetricDefinition(
        metric_name="WORKAREA_ONEPASS_PCT",
        display_label="Workarea Onepass %",
        metric_category="SPILL",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="Workarea Onepass %",
        chart_label="Onepass %",
        color="rgba(0, 188, 212, 0.92)",
        implemented=True,
        source_metric_name="WORKAREA_ONEPASS_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="WORKAREA_MULTIPASS_PCT",
        display_label="Workarea Multipass %",
        metric_category="SPILL",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="MEMORY",
        chart_title="Workarea Multipass %",
        chart_label="Multipass %",
        color="rgba(0, 151, 167, 0.92)",
        implemented=True,
        source_metric_name="WORKAREA_MULTIPASS_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="INSTANCE_IMBALANCE_PCT",
        display_label="Instance Imbalance %",
        metric_category="BALANCE",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="RAC",
        chart_title="Instance Imbalance %",
        chart_label="Instance imbalance %",
        color="rgba(102, 187, 106, 0.92)",
        implemented=False,
        reason_unavailable=(
            "True instance imbalance requires per-instance engineered "
            "aggregation, which is not yet supported in the DB-scoped feature "
            "layer."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="GC_WAIT_AVG_MS",
        display_label="GC Wait Avg",
        metric_category="LATENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="RAC",
        chart_title="GC Wait Avg",
        chart_label="GC wait avg ms",
        color="rgba(46, 125, 50, 0.92)",
        implemented=False,
        reason_unavailable=(
            "GC wait average latency is not currently exposed through the DB-scoped engineered metric view."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="INTERCONNECT_LATENCY_MS",
        display_label="Interconnect Latency",
        metric_category="LATENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="NETWORK",
        chart_title="Interconnect Latency",
        chart_label="Interconnect latency ms",
        color="rgba(2, 136, 209, 0.92)",
        implemented=False,
        reason_unavailable="Interconnect latency is not currently parsed into the feature layer.",
    ),
    EngineeredMetricDefinition(
        metric_name="NETWORK_ROUNDTRIP_P95_MS",
        display_label="Network Roundtrip P95",
        metric_category="LATENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="NETWORK",
        chart_title="Network Roundtrip P95",
        chart_label="Roundtrip p95 ms",
        color="rgba(3, 155, 229, 0.92)",
        implemented=False,
        reason_unavailable="Network roundtrip percentile is not derivable from current AWR parser output.",
    ),
    EngineeredMetricDefinition(
        metric_name="SQLNET_WAIT_PCT_DB_TIME",
        display_label="SQL*Net Wait %",
        metric_category="WAIT",
        unit="percent",
        numeric_format="pct_1",
        directionality="HIGH_IS_BAD",
        domain="NETWORK",
        chart_title="SQL*Net Wait %",
        chart_label="SQL*Net % DB time",
        color="rgba(25, 118, 210, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Specific SQL*Net wait percentage is not yet persisted separately "
            "from generic network waits."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="SMART_SCAN_PCT",
        display_label="Smart Scan %",
        metric_category="EFFICIENCY",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="EXADATA",
        chart_title="Smart Scan %",
        chart_label="Smart scan %",
        color="rgba(142, 36, 170, 0.92)",
        implemented=False,
        reason_unavailable="Current feature layer only carries a smart-scan flag, not a percentage metric.",
    ),
    EngineeredMetricDefinition(
        metric_name="FLASH_HIT_PCT",
        display_label="Flash Hit %",
        metric_category="EFFICIENCY",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="EXADATA",
        chart_title="Flash Hit %",
        chart_label="Flash hit %",
        color="rgba(123, 31, 162, 0.92)",
        implemented=False,
        reason_unavailable="Current feature layer only carries a flash-cache flag, not a percentage metric.",
    ),
    EngineeredMetricDefinition(
        metric_name="STORAGE_INDEX_SAVINGS_PCT",
        display_label="Storage Index Savings %",
        metric_category="EFFICIENCY",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="EXADATA",
        chart_title="Storage Index Savings",
        chart_label="Storage index savings %",
        color="rgba(103, 58, 183, 0.92)",
        implemented=True,
        source_metric_name="STORAGE_INDEX_SAVINGS_PCT",
    ),
    EngineeredMetricDefinition(
        metric_name="CELL_SINGLE_BLOCK_LATENCY_MS",
        display_label="Cell Single-Block Latency",
        metric_category="LATENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="EXADATA",
        chart_title="Cell Single-Block Latency",
        chart_label="Single-block latency ms",
        color="rgba(126, 87, 194, 0.92)",
        implemented=True,
        source_metric_name="CELL_SINGLE_BLOCK_LATENCY_MS",
    ),
    EngineeredMetricDefinition(
        metric_name="CELL_MULTIBLOCK_LATENCY_MS",
        display_label="Cell Multiblock Latency",
        metric_category="LATENCY",
        unit="ms",
        numeric_format="ms_2",
        directionality="HIGH_IS_BAD",
        domain="EXADATA",
        chart_title="Cell Multiblock Latency",
        chart_label="Multiblock latency ms",
        color="rgba(149, 117, 205, 0.92)",
        implemented=True,
        source_metric_name="CELL_MULTIBLOCK_LATENCY_MS",
    ),
    EngineeredMetricDefinition(
        metric_name="APPLY_EFFICIENCY_PCT",
        display_label="Apply Efficiency %",
        metric_category="EFFICIENCY",
        unit="percent",
        numeric_format="pct_1",
        directionality="LOW_IS_BAD",
        domain="DATAGUARD",
        chart_title="Apply Efficiency %",
        chart_label="Apply efficiency %",
        color="rgba(255, 179, 0, 0.92)",
        implemented=False,
        reason_unavailable=(
            "Apply efficiency is not currently derivable without a persisted redo-apply throughput metric."
        ),
    ),
    EngineeredMetricDefinition(
        metric_name="TRANSPORT_LAG_P95_SEC",
        display_label="Transport Lag P95",
        metric_category="LAG",
        unit="seconds",
        numeric_format="sec_1",
        directionality="HIGH_IS_BAD",
        domain="DATAGUARD",
        chart_title="Transport Lag P95",
        chart_label="Transport lag p95 sec",
        color="rgba(255, 202, 40, 0.92)",
        implemented=False,
        reason_unavailable="A snapshot-level percentile transport lag is not derivable from current AWR inputs.",
    ),
    EngineeredMetricDefinition(
        metric_name="APPLY_LAG_P95_SEC",
        display_label="Apply Lag P95",
        metric_category="LAG",
        unit="seconds",
        numeric_format="sec_1",
        directionality="HIGH_IS_BAD",
        domain="DATAGUARD",
        chart_title="Apply Lag P95",
        chart_label="Apply lag p95 sec",
        color="rgba(255, 214, 102, 0.92)",
        implemented=False,
        reason_unavailable="A snapshot-level percentile apply lag is not derivable from current AWR inputs.",
    ),
    EngineeredMetricDefinition(
        metric_name="REDO_APPLY_RATE_MBPS",
        display_label="Redo Apply Rate",
        metric_category="THROUGHPUT",
        unit="mbps",
        numeric_format="mbps_2",
        directionality="NEUTRAL",
        domain="DATAGUARD",
        chart_title="Redo Apply Rate",
        chart_label="Redo apply MB/s",
        color="rgba(255, 241, 118, 0.92)",
        implemented=False,
        reason_unavailable="Redo apply throughput is not currently parsed or persisted in FEATURE_JSON.",
    ),
)


ENGINEERED_METRIC_BY_NAME = {
    definition.metric_name: definition for definition in ENGINEERED_METRIC_CATALOG
}


def get_metric_definitions() -> tuple[EngineeredMetricDefinition, ...]:
    return ENGINEERED_METRIC_CATALOG


def get_metric_definition(metric_name: str) -> EngineeredMetricDefinition | None:
    return ENGINEERED_METRIC_BY_NAME.get(metric_name)


def get_implemented_metric_definitions() -> tuple[EngineeredMetricDefinition, ...]:
    return tuple(
        definition
        for definition in ENGINEERED_METRIC_CATALOG
        if definition.implemented and definition.source_metric_name
    )
