"""Screen 4 Comparative Review table rendering helpers.

These helpers render only from a validated Screen 4 deterministic comparison
output contract. They do not compute comparison data, render charts, or create
fallback evidence.
"""

from __future__ import annotations

from html import escape
from typing import Any


TABLE_PANEL_VISUALIZATIONS = {
    "metric_delta_table": "Metric Differences",
    "domain_delta_summary": "Domain Differences",
    "evidence_completeness_matrix": "Evidence Completeness",
    "confidence_basis_panel": "Confidence Basis",
    "missing_evidence_panel": "Missing Evidence",
}
TABLE_PANEL_ELIGIBILITY_NOTES = {
    "metric_delta_table": "Permitted by the validated contract when metric rows are present.",
    "domain_delta_summary": "Permitted by the validated contract when domain rows are present.",
    "evidence_completeness_matrix": "Available when evidence or missing-evidence category rows are present.",
    "confidence_basis_panel": "Available from the deterministic confidence basis.",
    "missing_evidence_panel": "Available when missing evidence or limitations are reported.",
}
DEFERRED_VISUALIZATIONS = {
    "time_series_overlay": "Time-series overlay requires aligned time-series rows.",
    "distribution_violin": "Distribution violin requires distribution sample rows.",
    "wait_class_movement_table": "Wait/event movement requires persistent wait/event identity.",
    "top_sql_movement_table": "SQL movement requires persistent SQL identity.",
    "top_event_movement_table": "Top event movement requires persistent event identity.",
}
DEFERRED_VISUALIZATION_LABELS = {
    "time_series_overlay": "Time-series Overlay",
    "distribution_violin": "Distribution / Violin Evidence",
    "wait_class_movement_table": "Wait/Event Movement",
    "top_sql_movement_table": "SQL Movement",
    "top_event_movement_table": "Top Event Movement",
}


def render_screen4_comparative_tables(comparative_state: dict[str, Any]) -> str:
    """Render output-ready Screen 4 Comparative Review tables and panels."""

    if not isinstance(comparative_state, dict):
        return ""
    if comparative_state.get("state") != "comparison_output_ready":
        return ""
    validation = comparative_state.get("validation")
    if not isinstance(validation, dict) or not validation.get("valid"):
        return ""
    contract = validation.get("output")
    if not isinstance(contract, dict) or not contract:
        return ""

    sections = [
        _render_readiness_banner(contract),
        _render_target_identity_summary(contract),
        _render_metric_delta_table(contract),
        _render_domain_delta_summary(contract),
        _render_evidence_completeness_matrix(contract),
        _render_visualization_eligibility_panel(contract),
        _render_confidence_basis_panel(contract),
        _render_missing_evidence_panel(contract),
    ]
    rendered_sections = [section for section in sections if section.strip()]
    if not rendered_sections:
        return ""
    return f"""
      <div class="screen4-comparative-output-tables"
           data-screen4-comparative-output-tables="validated-contract">
        {"".join(rendered_sections)}
      </div>
    """


def _render_readiness_banner(contract: dict[str, Any]) -> str:
    items = [
        ("Comparison ID", contract.get("comparison_id")),
        ("Validation Status", contract.get("validation_status")),
        ("Generated By", contract.get("generated_by")),
        ("Generated At", contract.get("generated_at")),
        ("Engine Version", contract.get("deterministic_engine_version")),
        ("Adapter Version", contract.get("adapter_version")),
        ("Contract Version", contract.get("contract_version")),
        ("Artifact Source", contract.get("artifact_source")),
        ("Workflow Request", contract.get("workflow_request_id")),
        ("Workflow Transaction", contract.get("workflow_transaction_id")),
    ]
    grid = _render_info_grid(items, "screen4-comparative-readiness-grid")
    if not grid:
        return ""
    return f"""
      <section class="evidence-pane screen4-comparative-readiness-banner"
               data-screen4-comparative-section="readiness-banner">
        <h3>Deterministic Comparison Output Readiness</h3>
        {grid}
      </section>
    """


def _render_target_identity_summary(contract: dict[str, Any]) -> str:
    target_a = contract.get("target_a_identity")
    target_b = contract.get("target_b_identity")
    alignment = contract.get("target_alignment")
    if not isinstance(target_a, dict) or not isinstance(target_b, dict):
        return ""
    if not isinstance(alignment, dict) or alignment.get("status") != "aligned":
        return ""
    card_a = _render_target_card(
        "Target A / Baseline",
        target_a,
        contract.get("baseline_run_id"),
        contract.get("source_scope"),
        contract.get("comparison_scope"),
        _target_snapshot_value(contract.get("input_snapshot_range"), "target_a"),
    )
    card_b = _render_target_card(
        "Target B / Candidate",
        target_b,
        contract.get("candidate_run_id"),
        contract.get("source_scope"),
        contract.get("comparison_scope"),
        _target_snapshot_value(contract.get("input_snapshot_range"), "target_b"),
    )
    cards = "".join(card for card in (card_a, card_b) if card.strip())
    if not cards:
        return ""
    alignment_grid = _render_info_grid(
        [
            ("Alignment Status", alignment.get("status")),
            ("Alignment Basis", ", ".join(_string_list(alignment.get("basis")))),
        ],
        "screen4-comparative-alignment-grid",
    )
    return f"""
      <section class="evidence-pane screen4-comparative-target-identity"
               data-screen4-comparative-section="target-identity">
        <h3>Target A vs Target B Identity</h3>
        <div class="subgrid screen4-comparative-target-identity-grid">
          {cards}
        </div>
        {alignment_grid}
      </section>
    """


def _render_target_card(
    title: str,
    identity: dict[str, Any],
    run_id: Any,
    source_scope: Any,
    comparison_scope: Any,
    snapshot_value: Any,
) -> str:
    items = [
        ("Run ID", _first_value(run_id, identity.get("run_id"))),
        ("AWR ID", identity.get("awr_id")),
        ("DB Name", _first_value(identity.get("db_name"), identity.get("database_name"))),
        ("DBID", identity.get("dbid")),
        ("Instance", _first_value(identity.get("instance"), identity.get("instance_name"))),
        ("Host", _first_value(identity.get("host"), identity.get("host_name"))),
        ("Snapshot / Window", _first_value(snapshot_value, identity.get("window"), identity.get("time_window"), identity.get("snapshot"), identity.get("snapshot_label"))),
        ("Source Type", identity.get("source_type")),
        ("Scope Type", identity.get("scope_type")),
        ("Scope Value", identity.get("scope_value")),
        ("Source Scope", source_scope),
        ("Comparison Scope", comparison_scope),
    ]
    grid = _render_info_grid(items, "screen4-comparative-target-card-grid")
    if not grid:
        return ""
    return f"""
      <article class="evidence-pane screen4-comparative-contract-target-card">
        <h4>{escape(title)}</h4>
        {grid}
      </article>
    """


def _render_evidence_completeness_matrix(contract: dict[str, Any]) -> str:
    evidence_rows = _dict_rows(contract.get("evidence_rows"))
    missing_rows = _dict_rows(contract.get("missing_evidence"))
    if not evidence_rows and not missing_rows:
        return ""
    categories = sorted(
        {
            _category_from_row(row)
            for row in evidence_rows + missing_rows
            if _category_from_row(row)
        }
    )
    rows = []
    for category in categories:
        evidence_count = sum(1 for row in evidence_rows if _category_from_row(row) == category)
        missing_count = sum(1 for row in missing_rows if _category_from_row(row) == category)
        if evidence_count and missing_count:
            status = "partial"
        elif evidence_count:
            status = "available"
        else:
            status = "missing"
        rows.append(
            {
                "category": category,
                "status": status,
                "evidence_rows": evidence_count,
                "missing_evidence": missing_count,
            }
        )
    if not rows:
        return ""
    table = _render_table(
        rows,
        [
            ("category", "Category"),
            ("status", "Status"),
            ("evidence_rows", "Evidence Rows"),
            ("missing_evidence", "Missing Evidence"),
        ],
        "screen4-comparative-evidence-completeness-table",
    )
    if not table:
        return ""
    return f"""
      <section class="evidence-pane screen4-comparative-evidence-completeness"
               data-screen4-comparative-section="evidence-completeness">
        <h3>Evidence Completeness</h3>
        {table}
      </section>
    """


def _render_domain_delta_summary(contract: dict[str, Any]) -> str:
    if not _visualization_allowed(contract, "domain_delta_summary"):
        return ""
    rows = _dict_rows(contract.get("domain_deltas"))
    if not rows:
        return ""
    normalized = []
    for row in rows:
        normalized.append(
            {
                "domain": _first_value(row.get("domain"), row.get("category")),
                "evidence_count": _first_value(row.get("evidence_count"), row.get("metric_count"), row.get("row_count")),
                "change_basis": _first_value(row.get("change_basis"), row.get("evidence_source")),
                "affected_metrics": ", ".join(_string_list(row.get("metrics") or row.get("affected_metrics"))),
                "difference_rows": _first_value(row.get("difference_rows"), row.get("metric_count")),
                "limitations": ", ".join(_string_list(row.get("limitations"))),
            }
        )
    table = _render_table(
        normalized,
        [
            ("domain", "Domain"),
            ("evidence_count", "Evidence Count"),
            ("change_basis", "Change Basis"),
            ("affected_metrics", "Affected Metrics"),
            ("difference_rows", "Difference Rows"),
            ("limitations", "Limitations"),
        ],
        "screen4-comparative-domain-delta-table",
    )
    if not table:
        return ""
    return f"""
      <section class="evidence-pane screen4-comparative-domain-delta-summary"
               data-screen4-comparative-section="domain-delta-summary">
        <h3>Domain Differences</h3>
        {table}
      </section>
    """


def _render_metric_delta_table(contract: dict[str, Any]) -> str:
    if not _visualization_allowed(contract, "metric_delta_table"):
        return ""
    rows = _dict_rows(contract.get("metric_deltas"))
    if not rows:
        return ""
    normalized = []
    for row in rows:
        normalized.append(
            {
                "metric": row.get("metric"),
                "domain": _first_value(row.get("domain"), row.get("category")),
                "target_a_value": _first_value(row.get("target_a_value"), row.get("baseline_value")),
                "target_b_value": _first_value(row.get("target_b_value"), row.get("candidate_value")),
                "delta": _first_value(row.get("delta"), row.get("difference")),
                "delta_percent": row.get("delta_percent"),
                "unit": row.get("unit"),
                "evidence_source": row.get("evidence_source"),
                "notes": _first_value(row.get("notes"), row.get("limitation")),
            }
        )
    table = _render_table(
        normalized,
        [
            ("metric", "Metric"),
            ("domain", "Domain / Category"),
            ("target_a_value", "Target A Value"),
            ("target_b_value", "Target B Value"),
            ("delta", "Delta"),
            ("delta_percent", "Delta Percent"),
            ("unit", "Unit"),
            ("evidence_source", "Evidence Source"),
            ("notes", "Notes / Limitations"),
        ],
        "screen4-comparative-metric-delta-table",
    )
    if not table:
        return ""
    return f"""
      <section class="evidence-pane screen4-comparative-metric-deltas"
               data-screen4-comparative-section="metric-delta-table">
        <h3>Metric Differences</h3>
        {table}
      </section>
    """


def _render_confidence_basis_panel(contract: dict[str, Any]) -> str:
    confidence = contract.get("confidence_basis")
    if not isinstance(confidence, dict):
        return ""
    grid = _render_info_grid(
        [
            ("Basis Type", confidence.get("basis_type")),
            ("Sample Count", confidence.get("sample_count")),
            ("Evidence Row Count", confidence.get("evidence_row_count")),
            ("Missing Evidence Count", confidence.get("missing_evidence_count")),
            ("Limitations", ", ".join(_string_list(confidence.get("limitations")))),
        ],
        "screen4-comparative-confidence-grid",
    )
    if not grid:
        return ""
    return f"""
      <section class="evidence-pane screen4-comparative-confidence-basis"
               data-screen4-comparative-section="confidence-basis">
        <h3>Deterministic Confidence Basis</h3>
        {grid}
      </section>
    """


def _render_missing_evidence_panel(contract: dict[str, Any]) -> str:
    missing_rows = _dict_rows(contract.get("missing_evidence"))
    messages = _useful_adapter_messages(contract.get("adapter_validation_messages"))
    confidence = contract.get("confidence_basis") if isinstance(contract.get("confidence_basis"), dict) else {}
    limitations = _string_list(confidence.get("limitations") if isinstance(confidence, dict) else None)
    if not missing_rows and not messages and not limitations:
        return ""
    parts = []
    if missing_rows:
        parts.append(
            _render_table(
                missing_rows,
                [
                    ("category", "Category"),
                    ("type", "Type"),
                    ("field", "Field"),
                    ("reference", "Reference"),
                    ("reason", "Reason"),
                    ("message", "Message"),
                    ("impact", "Impact"),
                    ("blocked_visualization", "Blocked Visualization"),
                ],
                "screen4-comparative-missing-evidence-table",
            )
        )
    if messages:
        parts.append(
            _render_table(
                messages,
                [
                    ("severity", "Severity"),
                    ("code", "Code"),
                    ("field", "Field"),
                    ("message", "Message"),
                ],
                "screen4-comparative-adapter-message-table",
            )
        )
    if limitations:
        parts.append(
            _render_bullets(
                limitations,
                "screen4-comparative-limitations-list",
            )
        )
    rendered = "".join(part for part in parts if part)
    if not rendered:
        return ""
    return f"""
      <section class="evidence-pane screen4-comparative-missing-evidence"
               data-screen4-comparative-section="missing-evidence">
        <h3>Missing Evidence / Limitations</h3>
        {rendered}
      </section>
    """


def _render_visualization_eligibility_panel(contract: dict[str, Any]) -> str:
    allowed = [item for item in _string_list(contract.get("allowed_visualizations")) if item in TABLE_PANEL_VISUALIZATIONS]
    deferred = [item for item in _string_list(contract.get("allowed_visualizations")) if item in DEFERRED_VISUALIZATIONS]
    rows = [
        {
            "visualization": TABLE_PANEL_VISUALIZATIONS[item],
            "status": "Available",
            "basis": TABLE_PANEL_ELIGIBILITY_NOTES.get(item),
        }
        for item in allowed
    ]
    rows.extend(
        {
            "visualization": DEFERRED_VISUALIZATION_LABELS[item],
            "status": "Blocked",
            "basis": DEFERRED_VISUALIZATIONS[item],
        }
        for item in deferred
    )
    if not rows:
        return ""
    table = _render_table(
        rows,
        [
            ("visualization", "Visualization"),
            ("status", "Status"),
            ("basis", "Basis"),
        ],
        "screen4-comparative-visualization-eligibility-table",
    )
    if not table:
        return ""
    return f"""
      <section class="evidence-pane screen4-comparative-visualization-eligibility"
               data-screen4-comparative-section="visualization-eligibility">
        <h3>Rendering Eligibility</h3>
        {table}
      </section>
    """


def _render_table(
    rows: list[dict[str, Any]],
    columns: list[tuple[str, str]],
    class_name: str,
) -> str:
    if not rows:
        return ""
    active_columns = [
        (key, label)
        for key, label in columns
        if any(_has_display_value(row.get(key)) for row in rows)
    ]
    if not active_columns:
        return ""
    header = "".join(f"<th>{escape(label)}</th>" for _, label in active_columns)
    body_rows = []
    for row in rows:
        cells = "".join(
            f"<td>{escape(_display_value(row.get(key)))}</td>"
            for key, _ in active_columns
        )
        body_rows.append(f"<tr>{cells}</tr>")
    return f"""
      <div class="table-wrap {escape(class_name, quote=True)}">
        <table>
          <thead><tr>{header}</tr></thead>
          <tbody>{"".join(body_rows)}</tbody>
        </table>
      </div>
    """


def _render_info_grid(
    items: list[tuple[str, Any]],
    class_name: str,
) -> str:
    rendered_items = []
    for label, value in items:
        if not _has_display_value(value):
            continue
        rendered_items.append(
            f"""
              <div class="info-item">
                <span>{escape(label)}</span>
                <strong>{escape(_display_value(value))}</strong>
              </div>
            """
        )
    if not rendered_items:
        return ""
    return f"""
      <div class="info-grid {escape(class_name, quote=True)}">
        {"".join(rendered_items)}
      </div>
    """


def _render_bullets(items: list[str], class_name: str) -> str:
    values = [item for item in items if _has_display_value(item)]
    if not values:
        return ""
    return f"""
      <ul class="{escape(class_name, quote=True)}">
        {"".join(f"<li>{escape(item)}</li>" for item in values)}
      </ul>
    """


def _visualization_allowed(contract: dict[str, Any], visualization: str) -> bool:
    return visualization in set(_string_list(contract.get("allowed_visualizations")))


def _dict_rows(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [row for row in value if isinstance(row, dict) and row]


def _useful_adapter_messages(value: Any) -> list[dict[str, Any]]:
    rows = _dict_rows(value)
    return [
        row
        for row in rows
        if any(_has_display_value(row.get(key)) for key in ("code", "message", "field"))
    ]


def _category_from_row(row: dict[str, Any]) -> str:
    category = _first_value(row.get("category"), row.get("type"), row.get("evidence_source"))
    if not _has_display_value(category):
        return ""
    text = str(category).strip()
    if "." in text:
        text = text.split(".", 1)[0]
    return text.replace("_differences", "").replace("_", " ")


def _target_snapshot_value(value: Any, prefix: str) -> Any:
    if not isinstance(value, dict):
        return None
    return _first_value(
        value.get(f"{prefix}_window"),
        value.get(f"{prefix}_snapshot"),
    )


def _string_list(value: Any) -> list[str]:
    if isinstance(value, list):
        return [str(item).strip() for item in value if _has_display_value(item)]
    if isinstance(value, tuple):
        return [str(item).strip() for item in value if _has_display_value(item)]
    if _has_display_value(value):
        return [str(value).strip()]
    return []


def _first_value(*values: Any) -> Any:
    for value in values:
        if _has_display_value(value):
            return value
    return None


def _display_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple)):
        return ", ".join(str(item) for item in value if _has_display_value(item))
    return str(value)


def _has_display_value(value: Any) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, (list, tuple, set, dict)):
        return bool(value)
    return True
